version: '3'

services:
  backend:
    image: "${{ secrets.DOCKER_HUB_USERNAME }}/cyf-backend:latest"
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

networks:
  default:
    external:
      name: bridge
