version: '3'

services:
  backend:
    image: "husseinbahdon/cyf-backend:latest"
    ports:
      - "5001:5000"
    environment:
      - NODE_ENV=production
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile

networks:
  default:
    external:
      name: cyfyoutube
