version: '3'

services:
  backend:
    image: "husseinbahdon/cyf-backend:latest"  
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    restart: always

networks:
  default:
    external:
      name: bridge
