name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  check_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check Modified Files
      id: check_files
      run: |
        echo "=============== list modified files ==============="
        git log -n 2 --pretty=format:%H -- client | xargs git diff --name-only
        
        echo "========== check paths of modified files =========="
        git log -n 2 --pretty=format:%H -- client | xargs git diff --name-only > files.txt
        while IFS= read -r file
        do
          echo $file
          if [[ $file != client/* ]]; then
            echo "This modified file is not under the 'client' folder."
            echo "::set-output name=run_deploy::false"
            break
          else
            echo "::set-output name=run_deploy::true"
          fi
        done < files.txt
    
    

    - name: Configure AWS credentials
      if: steps.check_files.outputs.run_deploy == 'true'
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Use Node.js 16
      if: steps.check_files.outputs.run_deploy == 'true'
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies and build
      if: steps.check_files.outputs.run_deploy == 'true'
      run: |
        cd client
        npm ci
        npm run build

    - name: Debug
      if: steps.check_files.outputs.run_deploy == 'true'
      run: |
        echo "AWS_REGION: us-west-2"
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        echo "S3_BUCKET: cyfyoutube"

    - name: Sync files to S3
      if: steps.check_files.outputs.run_deploy == 'true'
      run: aws s3 sync client/build s3://cyfyoutube
