name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: aws-configure
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies and build
      run: |
        cd client
        npm ci
        npm run build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: client/build

    - name: Set AWS credentials as outputs
      run: |
        echo "AWS_REGION=${{ steps.aws-configure.outputs.AWS_REGION }}" >> $GITHUB_ENV
        echo "AWS_ACCESS_KEY_ID=${{ steps.aws-configure.outputs.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ steps.aws-configure.outputs.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

  deploy:
    needs: setup
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build

    - name: Sync files to S3
      run: aws s3 sync client/build s3://cyfyoutube
      env:
        AWS_REGION: ${{ env.AWS_REGION }}
        AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}
