name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for changes in client folder
      id: check-changes
      run: |
        changes=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^client/")
        echo "Changes in client folder: $changes"
        echo "::set-output name=changes::$changes"

    - name: Configure AWS credentials
      if: steps.check-changes.outputs.changes
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Use Node.js 16
      if: steps.check-changes.outputs.changes
      uses: actions/setup-node@v4
      with:
        node-version: 16

    - name: Install dependencies and build
      if: steps.check-changes.outputs.changes
      run: |
        cd client
        npm ci
        npm run build

    - name: Debug
      run: |
        echo "AWS_REGION: us-west-2"
        echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
        echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
        echo "S3_BUCKET: cyfyoutube"

    - name: Sync files to S3
      if: steps.check-changes.outputs.changes
      run: aws s3 sync client/build s3://cyfyoutube
